name: gnss-sdr-next
version: 0.0.10
summary: GNSS-SDR, 'next' branch
description: GNSS-SDR, an open source Global Navigation Satellite Systems software-defined receiver.
confinement: strict

apps:
    gnss-sdr:
        command: environment gnss-sdr
        plugs: [network, network-bind, home]

    volk-gnsssdr-profile:
        command: environment volk_gnsssdr_profile
        plugs: [home]

    volk-gnsssdr-config-info:
        command: environment volk_gnsssdr-config-info
        plugs: [home]

    volk-profile:
        command: environment volk_profile
        plugs: [home]

    front-end-cal:
        command: environment front-end-cal
        plugs: [home]

parts:
    gnss-sdr:
        plugin: cmake
        source: https://github.com/gnss-sdr/gnss-sdr.git
        source-branch: next
        configflags:
            - -DENABLE_OSMOSDR=ON
            - -DENABLE_PACKAGING=ON
            - -DENABLE_UNIT_TESTING=OFF
        after: [environment]
        build-packages:
            - git
            - libboost-dev
            - libboost-date-time-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - libboost-thread-dev
            - libboost-serialization-dev
            - libboost-program-options-dev
            - liblog4cpp5-dev
            - libuhd-dev
            - libblas-dev
            - liblapack-dev
            - libarmadillo-dev
            - libgflags-dev
            - libgoogle-glog-dev
            - libgnutls28-dev
            - libgtest-dev
            - gnuradio-dev
            - gr-osmosdr
            - libmatio-dev
            - libpugixml-dev
            - libtool
            - autoconf
            - automake
            - unzip
        stage-packages:
            - git
            - libboost-dev
            - libboost-date-time-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - libboost-thread-dev
            - libboost-serialization-dev
            - libboost-program-options-dev
            - liblog4cpp5-dev
            - libuhd-dev
            - libblas-dev
            - liblapack-dev
            - libarmadillo-dev
            - libgflags-dev
            - libgoogle-glog-dev
            - libgnutls28-dev
            - libgtest-dev
            - gnuradio-dev
            - gr-osmosdr
            - libmatio-dev
            - libpugixml-dev

    environment:
        plugin: dump
        source: .
        organize:
            environment.sh: bin/environment
            wx.pth: usr/lib/wx/python/wx.pth
        stage-packages:
            - libbz2-1.0
            - libncursesw5
            - libtinfo5
            - libdb5.3
            - python-mako
            - python-six
            - try:
                - libzadc1
